In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("data//iris-flower-data.csv")
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
data.shape

(150, 5)

In [7]:
data['species'].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [8]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
data.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [11]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [12]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [14]:
x = data.iloc[:,0:4]
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [16]:
y = data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [18]:
x = scaler.fit_transform(x)
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [20]:
x_train.shape

(120, 4)

In [21]:
x_test.shape

(30, 4)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [23]:
pred = model.predict(x_test)

In [24]:
pred[0:5]

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [25]:
y_test[0:5]

113     Iris-virginica
62     Iris-versicolor
138     Iris-virginica
56     Iris-versicolor
92     Iris-versicolor
Name: species, dtype: object

In [27]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,pred)
accuracy

0.9333333333333333

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred)
cm

array([[ 7,  0,  0],
       [ 0, 10,  1],
       [ 0,  1, 11]])

In [29]:
result = pd.DataFrame(data=[y_test.values,pred], index = ['y_test','pred'])
result.transpose()

y_test             pred
0    Iris-virginica   Iris-virginica
1   Iris-versicolor  Iris-versicolor
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor  Iris-versicolor
5       Iris-setosa      Iris-setosa
6       Iris-setosa      Iris-setosa
7       Iris-setosa      Iris-setosa
8    Iris-virginica   Iris-virginica
9   Iris-versicolor  Iris-versicolor
10  Iris-versicolor  Iris-versicolor
11  Iris-versicolor  Iris-versicolor
12  Iris-versicolor   Iris-virginica
13   Iris-virginica  Iris-versicolor
14   Iris-virginica   Iris-virginica
15  Iris-versicolor  Iris-versicolor
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18   Iris-virginica   Iris-virginica
19  Iris-versicolor  Iris-versicolor
20   Iris-virginica   Iris-virginica
21  Iris-versicolor  Iris-versicolor
22   Iris-virginica   Iris-virginica
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26  Iris-versicolor  Iris-versicolor
27   Iris-virginica   Iris-virginica
28      Iris-setosa      Iris-setosa
29   Iris-virginica   Iris-virginica

In [30]:
correct_sum = [] 
for i in range(1,20):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    pred = model.predict(x_test)
    correct = np.sum(pred == y_test)
    correct_sum.append(correct) 

In [31]:
correct_sum

[np.int64(28),
 np.int64(25),
 np.int64(27),
 np.int64(28),
 np.int64(28),
 np.int64(27),
 np.int64(26),
 np.int64(28),
 np.int64(29),
 np.int64(29),
 np.int64(29),
 np.int64(29),
 np.int64(28),
 np.int64(29),
 np.int64(28),
 np.int64(29),
 np.int64(27),
 np.int64(27),
 np.int64(26)]

In [32]:
result = pd.DataFrame(data=correct_sum)
result.index = result.index+1
result.T

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19
0  28  25  27  28  28  27  26  28  29  29  29  29  28  29  28  29  27  27  26

In [33]:
model = KNeighborsClassifier(n_neighbors=6)
model.fit(x_train,y_train)
pred = model.predict(x_test)

In [34]:
accuracy_score(y_test,pred)

0.9

In [35]:
confusion_matrix(y_test,pred)

array([[ 7,  0,  0],
       [ 0, 11,  0],
       [ 0,  3,  9]])